# Generated by Django 4.2 on 2023-04-25 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_app', '0002_rename_category_expense_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='datetime',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
